server:
  port: 9000

spring:
  datasource:
    username: root
    password: zwtwoshichaoren
    url: jdbc:mysql://localhost:3306/nsh?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file: error.txt
  path: D:/log